# Generated by Django 4.2.6 on 2023-11-04 23:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('Nombre', models.CharField(max_length=100)),
                ('fnac', models.DateField()),
                ('correo', models.CharField(max_length=50)),
                ('contra', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Tareas',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('Nombre', models.CharField(max_length=100)),
                ('descripcion', models.CharField(max_length=200)),
                ('fecha_ini', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('ID_equipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aplicacion_1.equipo')),
            ],
        ),
        migrations.CreateModel(
            name='Miembros',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('ID_equipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aplicacion_1.equipo')),
                ('ID_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aplicacion_1.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Comunicaciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=15)),
                ('contenido', models.CharField(max_length=100)),
                ('fecha', models.DateField()),
                ('ID_equipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aplicacion_1.equipo')),
                ('ID_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aplicacion_1.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Acciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=15)),
                ('fecha', models.DateField()),
                ('ID_equipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aplicacion_1.equipo')),
                ('ID_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aplicacion_1.usuario')),
            ],
        ),
    ]
