# Generated by Django 4.2.6 on 2023-11-13 02:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion_1', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='fnac',
        ),
    ]
