# Generated by Django 4.2.6 on 2023-11-13 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion_1', '0002_remove_usuario_fnac'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='cont',
            field=models.IntegerField(default=0),
        ),
    ]
