# Generated by Django 4.2.6 on 2023-11-15 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion_1', '0005_alter_equipo_descripcion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipo',
            name='cantIntegrantes',
            field=models.IntegerField(default=1),
        ),
    ]
