# Generated by Django 4.2.6 on 2023-11-16 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion_1', '0006_alter_equipo_cantintegrantes'),
    ]

    operations = [
        migrations.AddField(
            model_name='tareas',
            name='estado',
            field=models.CharField(default='Incompleta', max_length=50),
        ),
        migrations.AddField(
            model_name='tareas',
            name='fecha_entrega',
            field=models.DateField(default='2023-12-31'),
        ),
    ]
