# Generated by Django 4.2.6 on 2023-11-16 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion_1', '0007_tareas_estado_tareas_fecha_entrega'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tareas',
            name='estado',
            field=models.CharField(default='Pendientes', max_length=50),
        ),
    ]
